stages:
  - verify
  - publish

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: $CI_REGISTRY_IMAGE

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

verify_docker_build:
  stage: verify
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  before_script:
    - docker version
    - docker info
  script:
    - docker build --pull -t "$IMAGE_NAME:verify-$CI_COMMIT_SHORT_SHA" .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  tags:
    - docker

publish_default_branch:
  stage: publish
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker version
    - docker info
  script:
    - docker build --pull -t "$IMAGE_NAME:$CI_DEFAULT_BRANCH" -t "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:$CI_DEFAULT_BRANCH"
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - docker push "$IMAGE_NAME:latest"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker

publish_tag:
  stage: publish
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker version
    - docker info
  script:
    - docker build --pull -t "$IMAGE_NAME:$CI_COMMIT_TAG" -t "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_TAG"
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - docker
